### ISSUE TITLE
Ubuntu as target OS

### ISSUE THREAD

**Issue by rvencu** [alexhorner/WD-DX4000#1]
Just curious if Ubuntu and Debian are so similar following your guide should be enough or not.

I know Ubuntu usually installs a lot of proprietary drivers, maybe some of them will be automatically setup like the fan for instance.

I guess just installing Debian then Bind on top I can get what I want anyway...

**Comment by alexhorner** [comment]
Hi @rvencu,

When I first started this project, the intent was in fact to install Ubuntu, not Debian. I am highly interested in getting Ubuntu working on this box, however there has been a roadblock for me on this.

I was not able to get the Ubuntu Server 20.04 LTS installer to start up on the serial console like I have done with Debian. If you are able to get Ubuntu to start on the serial console, I will hapily run through an installation on my own hardware to test all of the other parts of the guide for you, so you don't waste time installing it and finding some parts of the guide do not work. That way you can decide if you wish to do a final Debian or Ubuntu install knowing the limitations of both.

Thanks,

Alex

**Comment by rvencu** [comment]
Hi. I can confirm, Ubuntu server 20.04 is installing fine following your guide with more than 99% compatibility.

The only thing I noticed differently was on fancontrol pwmconfig where I was asked less questions than your docs provided.

As a small note: inserting the disks without reboot will NOT light the blue LED. But after reboot the LED are lighting just fine.

I also had to search for previous RAID (from windows installation) and remove it before I could follow up with the new raid creation.

Other than these minor bumps there is no problem whatsoever to setup Ubuntu. Thanks a lot for your effort to document all of it.

**Comment by alexhorner** [comment]
Hi @rvencu,

If possible, would you mind expanding on the LEDs please?

Would you also be able to provide information on how you set the Ubuntu installer up to work via serial console so I may document that please?

Thanks,

Alex

**Comment by rvencu** [comment]
There are 4 blue LEDs just below the LCD display, they are on when disks are used. After reboot they work fine. During the installation when disks are inserted they do not work (and I needed to double check if sdb and sdc are truly my inserted disks. No big deal.

I downloaded the 950MB installation iso for Ubuntu Server 20.04 and used latest Rufus to burn an installation USB stick. Then followed your docs. After first BIOS setup and reboot, there is a short amount of time where the console seems unresponsive but then the installation starts.

After some steps, the installation does not "see" the target disk but it offers either access to a terminal to partition and mount the target disk or instructions for SSH connection. it provides the installation user and password for SSH and it works fine.

After fixing the target disk, the installation does NOT rescan disks. I had to reboot once again and restart the installation for it to complete. Going to SSH terminal is better even second time. Normally after the setup the serial is not needed anymore but I found it convenient to watch the boot sequence.

**Comment by alexhorner** [comment]
Interesting, I never noticed the drive LEDs acted up during install but I didn't really pay attention. One issue I do have with them, is they are synchronised for all drive activity. On the windows installation they are split between the drives and only flash when the corresponding drive is active but with Debian they all flash in unison whenever any drive is accessed. I also have not got the buttons and the power LED communicating with the OS either.

Thanks for confirming what you've done, I shall attempt an Ubuntu installation when I get the chance to and I will also document how to clear the Intel RAID prior to installation

**Comment by rvencu** [comment]
As I have 2 drives in RAID, I think blinking on unison is OK as both drives are accessed at write operations at least. Not mind too much about them. They turn solid on at boot, then blink on usage.

**Comment by alexhorner** [comment]
Ah I have two sets of two drives so it can be a little confusing 😂

**Comment by alexhorner** [comment]
I am having great success with the Ubuntu installation right now. Once I have completed all of the guides myself, I will be finishing the writeup which I have already started and created a branch for.

**Comment by alexhorner** [comment]
The Ubuntu installation guide has now been completed. If you spot anything, please do let me know on this issue!

**Comment by rvencu** [comment]
All seems fine. I would add info about deleting windows raid configuration on disks.md since most of your readers will attempt to migrate from original config to Linux and will stumble on this issue.

**Comment by alexhorner** [comment]
Ah damn, forgot that again! I'll pop machine open again and write this up tonight. Thanks for checking through the new guide for me 😃

**Comment by alexhorner** [comment]
Hey there! I have now added the RAID configuration to the guide
