### ISSUE TITLE
Mislabel of wires for serial adapter in BeforeInstall.md

### ISSUE THREAD

**Issue by timedge5** [alexhorner/WD-DX4000#4]
Hi Alex,

Fantastic guide. This is just a tiny thing, barely worth an issue but it caught me up first time so might catch others.

In BeforeInstall.md where you show the close up of the wires, red goes to RX and grey to TX but below in the caption you say "on the pads (J23) Black is ground, Red is TX, Grey is RX.". The image is correct, red (middle pad) should be RX and grey (far left pad) should be TX.

Thx for putting this together!

**Comment by alexhorner** [comment]
Oh dear! I'll take a look at this in a bit and correct it.

Thanks for following the guide!

**Comment by alexhorner** [comment]
I have double checked and the text was correct for what I intended, however I can certainly see where the confusion lies so I have updated the document to be more clear.

Thanks for raising this, I have no doubt it would have caught someone else too so this is perfectly valid
