### ISSUE TITLE
Keyboard / Putty not working after "Serial Console Install" option

### ISSUE THREAD

**Issue by SpeedGP** [alexhorner/WD-DX4000#7]
Hi, for one, freaking awesome project, I'm super stoked to be able to get this setup!!!!

I am using an Arduino Uno as a USB to TTL converter, and it works really well. Putty connects, I can get into BIOS no problem and I have setup all of that info to be the same as yours. When I try to install Debian, it boots to the "GNU Grub" page, allows me to use the keyboard to move up and down and select "Serial Console Install", then at the "Select Language" page, I am unable to select anything or use the keyboard (local or putty) to control the screen / go to the next option.

Any ideas?

PS. Might be nice to add that you can use an Arduino as a TTL converter, and I actually already installed the missing SATA interface and am installing to that instead of the USB.

**Comment by alexhorner** [comment]
I have indeed seen the mod, just not any good implementation results. Maybe I'll give it a shot at some point, using a USB isn't ideal

Let me know how it goes!
