### ISSUE TITLE
Power button

### ISSUE THREAD

**Issue by jdbravo** [alexhorner/WD-DX4000#8]
Hello Alex!

I know that the buttons actions are in progress, but I would like to have some some directions to achieve the poweroff on the DX4000 when the power button is pressed.

I tried installing ACPID and setting the HandlePowerKey=poweroff without luck.

Thank you!

**Comment by alexhorner** [comment]
Hello @jdbravo,

The power button on the DX4000 is a standard ACPI power button, like on any other machine,

If you are failing to get a response upon pressing the power button, I suggest that your power button is either faulty and therefore not signalling to the motherboard its press, the flex cable between the front panel and the motherboard is (on either end) not seated correctly or damaged, or the machine is receiving the power button press, and promptly trying to shut itself down, but gets caught somewhere in the shutdown process, maybe waiting for a certain process to terminate which never does.

The last one about getting stuck would be easy to verify using the serial console, and may also be visible in a kernel log (if it gets written before a hard shutdown)

The button working or not - Well, can you turn the device on and force shut it off using it?

If this is not working for you, let me know and we can discuss in further depth how to resolve this one, but if it does, please close the issue with a solution comment so others who have the same issue can benefit from the solution.

Thanks,

Alex

**Comment by jdbravo** [comment]
Hello Alex,

You are right, it's a regular ACPI button.

The only thing that I had to do to enable it was edit the /etc/systemd/logind.conf and set the HandlePowerKey value for poweroff

And then...

systemctl restart systemd-logind.service

apcid was replaced for logind, probably after Debian Wheezy.

Thanks!

**Comment by alexhorner** [comment]
Hi @jdbravo,

Interesting! Are you using a custom install, or using one of my ISOs from https://github.com/alexhorner/WD-DX4000-Installer ?

Thanks,

Alex

**Comment by jdbravo** [comment]
Im using one of your released images. I installed OMV on it!

Thanks!

Jose
