### ISSUE TITLE
DX4000 Installer Missing startup.nsh

### ISSUE THREAD

**Issue by ganakee** [alexhorner/WD-DX4000#9]
Thank you for this great app.

I used the precompiled ISO images ([https://github.com/alexhorner/WD-DX4000-Installer](https://github.com/alexhorner/WD-DX4000-Installer)) to do a solderless install of Debian Buster. I installed to a separate USB drive plugged into the DX4000. The install took about an hour.

The installer instructions indicate that after installing, the DX4000 will not boot until startup.nsh is copied. The instructions here (respectfully) are vague. 

1) startup.nsh did not appear in my installer copy anywhere. 
2) It is unclear how to discover and mount the BOOT drive (not the install partition).

2) I shutdown the DX4000. I seperately downloaded the startup.sh for BUSTER at https://github.com/alexhorner/WD-DX4000-Installer/tree/master/Bullseye and saved to my local drive.
3) I removed the USB drive from the DX4000 and inserted into my Linux system. I used gparted to find and mount the BOOT partition (NOT the install partition--if you see a plethora of directories such as bin home usr etc. you mounted the wrong partition). The BOOT partition had only an EFI directory.
4) I copied the separately downloaded startup.nsh to the root of the BOOT partition.
4.5) I used ls -la to verify ownership as root root.
5) I unmounted the BOOT, removed the USB drive, inserted the USB into the DX4000 and booted. Now the DX4000 booted.

I might have been able to mount the USB with the installer. But lsblk did not show all the partitions or drives even after disk-detect.

**Comment by alexhorner** [comment]
Hi @ganakee

Please could you move this issue to the installer repo, as it is directly related to that, not to this.

In the mean time I will read through and prepare a response for you,

Sorry for the inconvenience,

Thank you
